name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.1.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Build
        run: flutter build apk

      - name: Run tests
        run: flutter test

      - name: Mutation testing
        run: flutter pub run test --runInIsolation && flutter pub run mutter test
